FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
WORKDIR /src
COPY PizzaClient.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app .
ENTRYPOINT [ "dotnet", "PizzaClient.dll" ]